# Generated by Django 5.0.6 on 2024-06-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='FavoriteModel',
        ),
        migrations.AlterField(
            model_name='favoritemodel',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profilemodel'),
        ),
    ]
