# Generated by Django 5.0.6 on 2024-06-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_favoritemodel_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemodel',
            old_name='profiles_id',
            new_name='profile_id',
        ),
        migrations.AlterUniqueTogether(
            name='favoritemodel',
            unique_together={('owner_id', 'profile_id')},
        ),
    ]
