# Generated by Django 5.0.6 on 2024-06-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profiles_id_favoritemodel_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritemodel',
            unique_together=set(),
        ),
    ]
