# Generated by Django 5.0.6 on 2024-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_favoritemodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='lan',
            field=models.CharField(default='9889678557698698', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.CharField(default='768768957867', max_length=255),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
