# Generated by Django 5.0.6 on 2024-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_city_user_lan_user_lat_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.CharField(max_length=255),
        ),
    ]
