# Generated by Django 5.0.6 on 2024-06-21 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profileimagemodel_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemodel',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileqew', to='users.profilemodel'),
        ),
        migrations.AlterField(
            model_name='favoritemodel',
            name='profile_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profilesweqweqwe', to='users.profilemodel'),
        ),
        migrations.AlterField(
            model_name='profileimagemodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.profilemodel'),
        ),
        migrations.AlterField(
            model_name='profilevideomodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profilemodel'),
        ),
    ]
