# Generated by Django 5.0.6 on 2024-06-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_favoritemodel_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemodel',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_profile', to='users.profilemodel'),
        ),
        migrations.AlterField(
            model_name='favoritemodel',
            name='profile_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_profiles', to='users.profilemodel'),
        ),
    ]
