# Generated by Django 5.0.6 on 2024-06-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_favoritemodel_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='rule',
            field=models.BooleanField(default=False),
        ),
    ]
