# Generated by Django 5.0.6 on 2024-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'verbose_name': 'Question Answer'},
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='role',
            field=models.CharField(choices=[('Customer', 'customer'), ('Expert', 'expert')], default='Customer', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='faqmodel',
            unique_together={('question', 'answer')},
        ),
        migrations.AlterModelTable(
            name='faqmodel',
            table='question_answer',
        ),
    ]
