# Generated by Django 5.0.6 on 2024-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_faqmodel_options_faqmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackimagemodel',
            name='image',
            field=models.ImageField(upload_to='FeedbackImage/'),
        ),
    ]
