# Generated by Django 5.0.6 on 2024-06-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_feedbackimagemodel_profile_id'),
        ('users', '0006_alter_favoritemodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackimagemodel',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profilemodel'),
        ),
    ]
