# Generated by Django 5.0.6 on 2024-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_feedbackimagemodel_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
