# Generated by Django 5.0.6 on 2024-06-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_alter_feedbackmodel_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='profile_id',
        ),
    ]
