# Generated by Django 5.0.6 on 2024-06-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_remove_feedbackmodel_profile_id'),
        ('users', '0009_alter_profileimagemodel_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackimagemodel',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.profilemodel'),
        ),
    ]
